name: h_order
description: H Order application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^2.0.0

  signalr_core: ^1.0.8

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  json_annotation: ^3.1.1
  date_format: ^1.0.9

  sentry_flutter: ^4.0.6

  shared_preferences: ^2.0.5

  flutter_svg: ^0.19.3
  flutter_inner_drawer: ^1.0.0+1
  animated_text_kit: ^4.0.0
  fluttertoast: ^7.1.8
  flutter_local_notifications: ^4.0.1+2

  device_info: ^2.0.0
  package_info: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2
  mobx_codegen: ^1.1.2
  json_serializable: ^4.0.3
  retrofit: ^1.3.4+1

flutter:
  uses-material-design: true